jobs:
  # Replace params / app_name with your heroku app name
  - name: heroku-deploy
    plan:
      - aggregate:
          - get: ExamPGR301-Infra
          - get: heroku-docker-image
            trigger: true
            passed: [build-push-heroku]
      - task: publish
        file: ExamPGR301-Infra/concourse/heroku/task.yml
        input_mapping: {source: heroku-docker-image}
        params:
          github_token: ((github_token))
          heroku_api_key: ((heroku_api_key))
          heroku_provider: ((heroku_provider))
          heroku_app_name: ((heroku_app_name))

# Old heroku deploy using heroku slugs. Is working, uncomment to test if you want.

#  - name: heroku-deploy
#    plan:
#      - aggregate:
#        - get: ExamPGR301-Infra
#        - get: ExamPGR301-App
#          trigger: true
#      - task: mvn_build
#        file: ExamPGR301-Infra/concourse/java/task.yml
#        input_mapping: {source: ExamPGR301-App}
#      - task: sync-heroku
#        file: ExamPGR301-Infra/concourse/heroku/heroku_sync.yml
#        input_mapping: {source: ExamPGR301-App}
#        params:
#          github_token: ((github_token))
#          heroku_api_key: ((heroku_api_key))
#          heroku_provider: ((heroku_provider))
#          heroku_app_name: ((heroku_app_name))

  - name: infra
    plan:
      - aggregate:
          - get: ExamPGR301-Infra
      - task: apply
        file: ExamPGR301-Infra/concourse/terraform/task.yml
        input_mapping: {source: ExamPGR301-Infra}
        params:
          github_token: ((github_token))
          heroku_api_key: ((heroku_api_key))
          heroku_provider: ((heroku_provider))
          command: apply
          directories: |
            terraform
      - put: ExamPGR301-Infra
        params:
          repository: with-state
          rebase: true

  # Method to push docker image to dockerhub
  - name: build-push-dockerhub
    public: true
    serial: true
    plan:
      - get: ExamPGR301-App
      - put: dockerhub-docker-image
        params:
          build: ExamPGR301-App

  # Method to push docker image to heroku registry
  - name: build-push-heroku
    public: true
    serial: true
    plan:
      - get: ExamPGR301-App
        trigger: true
      - put: heroku-docker-image
        params:
          build: ExamPGR301-App

resources:

  # Github app resource
  - name: ExamPGR301-App
    type: git
    source:
      uri: git@github.com:UkjentFlodsvin/PGR301Exam-App.git
      branch: master
      private_key: ((deploy_key_app))

  # Github infra resource
  - name: ExamPGR301-Infra
    type: git
    source:
      uri: git@github.com:UkjentFlodsvin/PGR301Exam-Infra.git
      branch: master
      private_key: ((deploy_key_infra))

  # Docker image to dockerhub resource
  - name: dockerhub-docker-image
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/bookapi

  # Docker image to heroku registry resource
  - name: heroku-docker-image
    type: docker-image
    source:
      email: ((heroku_provider))
      username: ((heroku_provider))
      password: ((heroku_api_key))
      repository: registry.heroku.com/((heroku_app_name))/web
