jobs:
  # Replace params / app_name with your heroku app name
  - name: deploy-app
    plan:
      - aggregate:
          - get: ExamPGR301-App
          - get: ExamPGR301-Infra
      - task: build
        file: ExamPGR301-Infra/concourse/heroku/task.yml
        input_mapping: {source: ExamPGR301-App}
        params:
          directories: |
            terraform

  - name: infra
    plan:
      - aggregate:
          - get: ExamPGR301-Infra
      - task: apply
        file: ExamPGR301-Infra/concourse/terraform/task.yml
        input_mapping: {source: ExamPGR301-Infra}
        params:
          github_token: ((github_token))
          heroku_api_key: ((heroku_api_key))
          heroku_provider: ((heroku_provider))
          command: apply
          directories: |
            terraform
      - put: ExamPGR301-Infra
        params:
          repository: with-state
          rebase: true

resources:

  # Replace with your own repository
#  - name: ExamPGR301-App
#    type: git
#    source:
#      uri: git@github.com:UkjentFlodsvin/PGR301Exam-App.git
#      branch: master
#      private_key: ((deploy_key_app))

  # Replace with your own repository
  - name: ExamPGR301-Infra
    type: git
    source:
      uri: git@github.com:UkjentFlodsvin/PGR301Exam-Infra.git
      branch: master
      private_key: ((deploy_key_infra))